### ISSUE TITLE
Size to Dynamic Content?

### ISSUE THREAD

**Issue by christopheclc** [perimeter-inc/LegacyScrollView#3]
Hi,

Thank you so much for providing this library! It is very nice to have.

I'm having an issue which is that the UIScrollView doesn't seem to resize its height for vertical dynamic content. How can I get it to properly resize when the height of the content changes with dynamic content such as web requests or images loading asynchronously?

**Comment by bwide** [comment]
`updateView()` in `LegacyUIScrollView` should be taking care of that, but maybe there's a scenario where it doesn't update.

Here's a working example of content that is able to update it's height currently

```swift
struct Test: View {
    
    @State var tests: [String] = []
    
    var body: some View {
        LegacyScrollView {
            ForEach(tests, id: \.self) {
                Text($0)
            }
        }
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 7) {
                tests = (0...100).map({ _ in
                    "test data"
                })
            }
        }
    }
}
```
maybe there's something in your scrollView's content? could you provide an example of how to reproduce this behavior?

**Comment by christopheclc** [comment]
Thank you so much for your help!

After digging into the issue a lot more, I found it was due to having a @Published variable in a view model class that was probably being re-created in the view hierarchy in my content within the UIScrollView. Once I moved the model class outside of the UIScrollView hierarchy, everything worked perfectly.

I apologize for the trouble.
